### A MNIST-like fashion product database

In this, we classify the images into respective classes given in the dataset. We use a Neural Net and a Deep Neural Net in Keras to solve this and check the accuracy scores.

### Load tensorflow

In [0]:
import tensorflow as tf
tf.set_random_seed(42)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
tf.__version__

'1.14.0'

### Collect Data

In [4]:
import keras

Using TensorFlow backend.


In [5]:
(trainX, trainY), (testX, testY) = keras.datasets.fashion_mnist.load_data()

4431872/4422102 [==============================] - 1s 0us/step


In [7]:
print(trainX)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [8]:
print(trainY)

[9 0 0 ... 3 0 5]


### Convert both training and testing labels into one-hot vectors.

**Hint:** check **tf.keras.utils.to_categorical()**

In [11]:
tf.keras.utils.to_categorical(trainY)
tf.keras.utils.to_categorical(testY)

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [30]:
print(trainY.shape)
print('First 5 examples now are: ', trainY[0:5])

(60000,)
('First 5 examples now are: ', array([9, 0, 0, 3, 0], dtype=uint8))


In [31]:
print(trainX.shape)
print('First 5 examples now are: ', trainX[0:5])

(60000, 28, 28)
('First 5 examples now are: ', array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
  

### Visualize the data

Plot first 10 images in the triaining set and their labels.

### Build a neural Network with a cross entropy loss function and sgd optimizer in Keras. The output layer with 10 neurons as we have 10 classes.

In [0]:
  from keras.models import Sequential
  from keras.layers import Dense
  from keras.layers import Flatten
  from keras import optimizers
  
  model = Sequential()
  model.add(Flatten())
  model.add(Dense(10, input_dim=3, activation='relu'))
  model.add(Dense(1))
  
  #sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
  model.compile(loss='mean_squared_error', optimizer='sgd')
    

### Execute the model using model.fit()

In [41]:
model.fit(trainX, trainY, epochs=10, batch_size=500)

W0730 17:15:49.926441 140313441552256 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

W0730 17:15:49.948050 140313441552256 deprecation_wrapper.py:119] From /usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py:973: The name tf.assign is deprecated. Please use tf.compat.v1.assign instead.



Epoch 1/10
60000/60000 [==============================] - 7s 111us/step - loss: nan
Epoch 2/10
60000/60000 [==============================] - 0s 8us/step - loss: nan
Epoch 3/10
60000/60000 [==============================] - 0s 8us/step - loss: nan
Epoch 4/10
60000/60000 [==============================] - 0s 8us/step - loss: nan
Epoch 5/10
60000/60000 [==============================] - 0s 8us/step - loss: nan
Epoch 6/10
60000/60000 [==============================] - 0s 7us/step - loss: nan
Epoch 7/10
60000/60000 [==============================] - 0s 8us/step - loss: nan
Epoch 8/10
60000/60000 [==============================] - 0s 8us/step - loss: nan
Epoch 9/10
60000/60000 [==============================] - 1s 9us/step - loss: nan
Epoch 10/10
60000/60000 [==============================] - 0s 8us/step - loss: nan


### In the above Neural Network model add Batch Normalization layer after the input layer and repeat the steps.

In [0]:
  model = Sequential()
  model.add(Flatten())
  model.add(Dense(10, input_dim=3, activation='relu'))
  keras.layers.BatchNormalization(axis=-1, momentum=0.99, epsilon=0.001, center=True, scale=True, beta_initializer='zeros')
  model.add(Dense(1))
  
  #sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
  model.compile(loss='mean_squared_error', optimizer='sgd')


### Execute the model

In [43]:
model.fit(trainX, trainY, epochs=10, batch_size=500)

Epoch 1/10
60000/60000 [==============================] - 1s 12us/step - loss: nan
Epoch 2/10
60000/60000 [==============================] - 1s 9us/step - loss: nan
Epoch 3/10
60000/60000 [==============================] - 1s 9us/step - loss: nan
Epoch 4/10
60000/60000 [==============================] - 1s 9us/step - loss: nan
Epoch 5/10
60000/60000 [==============================] - 1s 9us/step - loss: nan
Epoch 6/10
60000/60000 [==============================] - 0s 8us/step - loss: nan
Epoch 7/10
60000/60000 [==============================] - 0s 8us/step - loss: nan
Epoch 8/10
60000/60000 [==============================] - 0s 7us/step - loss: nan
Epoch 9/10
60000/60000 [==============================] - 0s 8us/step - loss: nan
Epoch 10/10
60000/60000 [==============================] - 0s 8us/step - loss: nan


### Customize the learning rate to 0.001 in sgd optimizer and run the model

### Build the Neural Network model with 3 Dense layers with 100,100,10 neurons respectively in each layer. Use cross entropy loss function and singmoid as activation in the hidden layers and softmax as activation function in the output layer. Use sgd optimizer with learning rate 0.03.

In [0]:
  model = Sequential()
  model.add(Flatten())
  model.add(Dense(100, input_dim=3, activation='sigmoid'))
  model.add(Dense(100,activation='sigmoid'))
  model.add(Dense(10,activation='sigmoid'))
  model.add(Dense(1))
  
  #sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
  model.compile(loss='mean_squared_error', optimizer='sgd')


## Review model

### Run the model

In [46]:
model.fit(trainX, trainY, epochs=10, batch_size=500)

Epoch 1/10
60000/60000 [==============================] - 1s 22us/step - loss: 8.5193
Epoch 2/10
60000/60000 [==============================] - 1s 17us/step - loss: 2.9381
Epoch 3/10
60000/60000 [==============================] - 1s 16us/step - loss: 2.3525
Epoch 4/10
60000/60000 [==============================] - 1s 17us/step - loss: 2.1051
Epoch 5/10
60000/60000 [==============================] - 1s 16us/step - loss: 1.9860
Epoch 6/10
60000/60000 [==============================] - 1s 17us/step - loss: 1.8942
Epoch 7/10
60000/60000 [==============================] - 1s 16us/step - loss: 1.8953
Epoch 8/10
60000/60000 [==============================] - 1s 16us/step - loss: 1.8851
Epoch 9/10
60000/60000 [==============================] - 1s 16us/step - loss: 1.9056
Epoch 10/10
60000/60000 [==============================] - 1s 16us/step - loss: 1.8572
